name:                alien-alphabet
version:             0.1.0.0
github:              "sstoltze/alien-alphabet"
license:             BSD3
author:              "Sarah Stoltze"
maintainer:          "sstoltze@gmail.com"
copyright:           "2021 Sarah Stoltze"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sstoltze/alien-alphabet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  alien-alphabet-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alien-alphabet

tests:
  alien-alphabet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alien-alphabet
