name:                amqp-tester
version:             0.1.0.0
github:              "sstoltze/amqp-tester"
license:             BSD3
author:              "Sarah Stoltze"
maintainer:          "sstoltze@gmail.com"
copyright:           "2022 Sarah Stoltze"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sstoltze/amqp-tester#readme>

dependencies:
  - base >= 4.7 && < 5
  - microlens
  - proto-lens
  - proto-lens-protobuf-types
  - text
  - amqp
  - dotenv
  - bytestring
  - req
  - aeson
  - mtl
  - random
  - containers

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

extra-source-files:
  - proto/**/*.proto

library:
  source-dirs: src
  dependencies:
    - base
    - proto-lens-runtime

  generated-exposed-modules:
    - Proto.Test
    - Proto.Test_Fields


executables:
  amqp-tester-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - amqp-tester

tests:
  amqp-tester-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - amqp-tester
