name:                service-search-suggestions
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/sstoltze/protoc-person#readme
license:             BSD3
author:              Sarah Stoltze
maintainer:          sstoltze@gmail.com
copyright:           2021 Sarah Stoltze
category:            Web

dependencies:
  - base
  - microlens
  - proto-lens
  - text
  # https://hackage.haskell.org/package/amqp-0.22.0/docs/Network-AMQP.html
  - amqp
  - dotenv
  - bytestring
  - req
  - aeson
  - mtl

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

extra-source-files: proto/**/*.proto

library:
  dependencies:
    - base
    - proto-lens-runtime

  exposed-modules:
    - Proto.Search
    - Proto.Search_Fields

executables:
  service-search-suggestions:
    main: Main.hs
    source-dirs:
      - app
      - src
    dependencies:
      - service-search-suggestions

  send-test-requests:
    main: Send.hs
    source-dirs:
      - test
      - src
    dependencies:
      - service-search-suggestions
      - random
