name:                github
version:             0.1.0.0
github:              "sstoltze/github"
license:             BSD3
author:              "Sarah Stoltze"
maintainer:          "sstoltze@gmail.com"
copyright:           "2021 Sarah Stoltze"

extra-source-files:
  - README.md
  - ChangeLog.md

  # Metadata used when publishing your package
  # synopsis:            Short description of your package
  # category:            Web

  # To avoid duplicated efforts in documentation and dealing with the
  # complications of embedding Haddock markup inside cabal files, it is
  # common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sstoltze/github#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - http-types
  - github-rest
  - bytestring
  - utf8-string
  - aeson
  - containers
  - base64
  - directory
  - filepath

library:
  source-dirs: src

executables:
  codeowners:
    main:                Main.hs
    source-dirs:         codeowners
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - github
      - dotenv
      - streaming

tests:
  github-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - github
