name:                rpc-client
version:             0.1.0.0
github:              "sstoltze/rpc-client"
license:             BSD3
author:              "Sarah Stoltze"
maintainer:          "sstoltze@gmail.com"
copyright:           "2021 Sarah Stoltze"

extra-source-files:
- README.md
- ChangeLog.md
- proto/**/*.proto

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sstoltze/rpc-client#readme>

dependencies:
- base >= 4.7 && < 5
- microlens
- proto-lens
- text
- amqp
- bytestring
- containers
- random

custom-setup:
  dependencies:
  - base
  - Cabal
  - proto-lens-setup

build-tools: proto-lens-protoc:proto-lens-protoc

library:
  source-dirs: src
  dependencies:
  - base
  - proto-lens-runtime
  - proto-lens-protobuf-types
  generated-exposed-modules:
  # Add generated protobuf files here
  # e.g. for 'test.proto'
  - Proto.Test
  - Proto.Test_Fields

executables:
  rpc-client-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpc-client
    - dotenv

tests:
  rpc-client-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rpc-client
    - dotenv
